export enum MultiplierEventType {
  LATE_CONTRIBUTION = 'LATE_CONTRIBUTION',
  ON_TIME_CONTRIBUTION = 'ON_TIME_CONTRIBUTION',
  CONSECUTIVE_ON_TIME_CONTRIBUTIONS = 'CONSECUTIVE_ON_TIME_CONTRIBUTIONS',

  LATE_REPAYMENT = 'LATE_REPAYMENT',
  ON_TIME_REPAYMENT = 'ON_TIME_REPAYMENT',

  EARLY_FULL_PAYOFF = 'EARLY_FULL_PAYOFF',
}
